# Generated by Django 3.2.13 on 2022-06-27 06:49

from django.db import migrations, models
import verification.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=100)),
                ('holder_name', models.CharField(max_length=100)),
                ('document', models.FileField(blank=True, upload_to=verification.models.Document.pdf_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
