# Generated by Django 3.2.13 on 2022-06-27 07:08

from django.db import migrations, models
import verification.models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=verification.models.Document.pdf_upload_path),
        ),
    ]
